#!/bin/bash

spaces (){
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({id, name, windows}) | sort')
	ACTIVE_WORKSPACE=$(hyprctl activeworkspace -j | jq '.id')
    echo $WORKSPACE_WINDOWS | jq --argjson aws "$ACTIVE_WORKSPACE" --slurp -Mc '.[] | map(if .id == $aws then . + {active: true} else . + {active: false} end)'
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
